language: objective-c
osx_image: xcode11.3
before_install:
  - openssl aes-256-cbc -K $encrypted_6679cbc0abf1_key -iv $encrypted_6679cbc0abf1_iv -in GoogleService-Info.plist.enc -out GoogleService-Info.plist -d
  - brew update
  - brew install bartycrouch swiftgen
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild -workspace "CampNet iOS.xcworkspace" -scheme "CampNet iOS" -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 11,OS=13.3" build test | xcpretty
after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'CampNet'
notifications:
  slack: campnet:We503kNJbkcYp8UH3UPLS3RM
