language: objective-c
osx_image: xcode10.1
before_install:
  - brew update
  - brew install bartycrouch swiftgen
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild -workspace "CampNet iOS.xcworkspace" -scheme "CampNet iOS" -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone XR,OS=12.1" build test | xcpretty
after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'CampNet'
notifications:
  slack: campnet:We503kNJbkcYp8UH3UPLS3RM
