language: objective-c
osx_image: xcode9
before_install:
  - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild -workspace "CampNet iOS.xcworkspace" -scheme "CampNet iOS" -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone X,OS=11.0" build test | xcpretty
after_success:
  - bash <(curl -s https://codecov.io/bash)
