# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
  "iPad Pro (12.9-inch) (3rd generation)",
  "iPad Pro (11-inch)",
  "iPad Pro (12.9-inch) (2nd generation)",
  "iPad Pro (10.5-inch)",
  "iPad Pro (9.7-inch)",
  "iPhone XS Max",
  "iPhone XS",
  "iPhone 8 Plus",
  "iPhone 8",
  "iPhone SE",
  "iPhone 4s",
])

languages([
  "en-US",
  "zh-Hans",
  "zh-Hant",
])

# The name of the scheme which contains the UI Tests
scheme "CampNet iOS"

# Where should the resulting screenshots be stored?
# output_directory "./screenshots"

# clear_previous_screenshots true # remove the '#' to clear all previously generated screenshots before creating new ones

# Choose which project/workspace to use
# project "./Project.xcodeproj"
# workspace "./Project.xcworkspace"

# Arguments to pass to the app on launch. See https://github.com/fastlane/fastlane/tree/master/snapshot#launch-arguments
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane snapshot --help
