ssids:
  - Tsinghua
  - Tsinghua-5G

billing:
  student:
    max_online_num: 3
    base: 0
    cycle: month
    steps:
      - [20, 1]
      - [30, 2]
      - [40, 3]
      - [50, 5]
  staff:
    max_online_num: 3
    base: 12
    cycle: month
    steps:
      - [20, 1]
      - [30, 2]
      - [40, 3]
      - [50, 5]
  temporary:
    max_online_num: 1
    base: 10
    cycle: day
    steps:
      - [2, 5]

sessions:
  usereg:
    - method: POST
      url: http://usereg.tsinghua.edu.cn/do.php
      params:
        action: login
        user_login_name: "{username}"
        user_password: "{password.md5}"
      expect: \Aok\Z
      errors:
        unauthorized.username: \A用户不存在\Z
        unauthorized.password: \A密码错误\Z

actions:
  login:
    - method: POST
      url: http://net.tsinghua.edu.cn/do_login.php
      params:
        action: login
        username: "{username}"
        password: "{MD5_HEX}{password.md5}"
        ac_id: "1"
      expect: \A(Login is successful.|IP has been online, please logout.)\Z
      errors:
        unauthorized.username: \AE2531
        unauthorized.password: \AE2553
        arrears: \AE(2616|3001|3004)

  status:
    - url: http://net.tsinghua.edu.cn/rad_user_info.php
      expect: \A\Z|\A([^,]*,){12}[^,]*\Z
      post_hook: |
        (resp) => {
            if (!resp)
                return {status: "offline"};

            let info = resp.split(",");
            return {
                username: info[0],
                start_time: new Date(Number(info[1]) * 1000),
                usage: Number(info[3]),
                total_usage: Number(info[6]),
                ip: info[8],
                balance: Number(info[11])
            };
        }

  profile:
    - session: usereg
      url: http://usereg.tsinghua.edu.cn/user_info.php
      errors:
        session_timeout: \A请登录先\Z
      vars:
        billing: (//td[@class="maintd"])[4]
        name: (//td[@class="maintd"])[6]
        usage: number(substring-before((//td[@class="maintd"])[26], "("))
        balance: number(substring-before((//td[@class="maintd"])[34], "元"))

    - session: usereg
      url: http://usereg.tsinghua.edu.cn/modify_online_num.php
      errors:
        session_timeout: \A请登录\Z
      vars:
        custom_max_online_num: number(//option[@selected]/@value)

    - session: usereg
      url: http://usereg.tsinghua.edu.cn/online_user_ipv4.php
      errors:
        session_timeout: \A请登录先\Z
      vars:
        id: //tr[position()>=2]//input/@value
        ip: //tr[position()>=2]/td[2]
        start_time: //tr[position()>=2]/td[3]
        usage: //tr[position()>=2]/td[4]
        mac: //tr[position()>=2]/td[8]
        device: //tr[position()>=2]/td[12]
      date_formatter: yyyy-MM-dd HH:mm:ss

  modify_custom_max_online_num:
    - session: usereg
      method: POST
      url: http://usereg.tsinghua.edu.cn/modify_online_num.php
      params:
        action: mod
        user_max_online_num: "{new_custom_max_online_num}"
      expect: 联网数已修改
      errors:
        session_timeout: \A请登录\Z

  login_ip:
    - session: usereg
      method: POST
      url: http://usereg.tsinghua.edu.cn/ip_login.php
      params:
        n: "100"
        is_pad: "1"
        type: "10"
        action: do_login
        user_ip: "{new_ip}"
        drop: "0"
      expect: 上线请求已发送
      errors:
        offcampus: \Aip地址非校内网段\Z
        session_timeout: \A请登录先\Z

  logout_session:
    - session: usereg
      method: POST
      url: http://usereg.tsinghua.edu.cn/online_user_ipv4.php
      params:
        action: drops
        user_ip: "{session.id},"
      expect: \A下线请求已发送\Z
      errors:
        session_timeout: \A请登录先\Z

  history:
    - session: usereg
      url: http://usereg.tsinghua.edu.cn/user_detail_list.php
      params:
        action: query
        start_time: "{start_time:yyyy-MM-dd}"
        end_time: "{end_time:yyyy-MM-dd}"
        offset: "1000000000"
      vars:
        ip: //tr[position()>=2]/td[2]
        start_time: //tr[position()>=2]/td[3]
        end_time: //tr[position()>=2]/td[4]
        usage: //tr[position()>=2]/td[6]
        cost: //tr[position()>=2]/td[8]
        mac: //tr[position()>=2]/td[10]
        device: //tr[position()>=2]/comment()[last()]
      date_formatter: yyyy-MM-dd HH:mm:ss

  logout:
    method: POST
    url: http://net.tsinghua.edu.cn/do_login.php
    params:
      action: logout
    expect: \A(Logout is successful.|You are not online.)\Z  # TODO: Confirm.
