ssids:
  - Tsinghua
  - Tsinghua-5G

billing:
  student:
    base: 0
    cycle: month
    steps:
      - [20, 1]
      - [30, 2]
      - [40, 3]
      - [50, 5]
  staff:
    base: 12
    cycle: month
    steps:
      - [20, 1]
      - [30, 2]
      - [40, 3]
      - [50, 5]
  temporary:
    base: 10
    cycle: day
    steps:
      - [2, 5]

devices:
  Android: android
  IOS-Client: ios
  iPad: ios.ipad
  iPhone: ios.iphone
  Linux: linux
  Mac OS: macos
  Unknown: unknown
  Windows 7: windows.7
  Windows 8: windows.8
  Windows NT: windows
  Windows XP: windows.xp
  Windows-Client: windows.client

actions:
  login:
    - method: POST
      url: http://net.tsinghua.edu.cn/do_login.php
      params:
        action: login
        username: "{username}"
        password: "{MD5_HEX}{password.md5}"
        ac_id: "1"
      result:
        ok: Login is successful|IP has been online, please logout
        unauthorized.username: E2531
        unauthorized.password: E2553
        arrears: E2616|E3001|E3004

  login_ip:
    - login_usereg
    - method: POST
      url: http://usereg.tsinghua.edu.cn/ip_login.php
      params:
        n: "100"
        is_pad: "1"
        type: "10"
        action: do_login
        user_ip: "{ip}"
        drop: "0"
      result:
        ok: 上线请求已发送

  status:
    - url: http://net.tsinghua.edu.cn/rad_user_info.php
      result: |
        let resp = $("body").text().trim();
        let vars = resp.split(",");

        let COLS = 13;
        if (vars.length != COLS)
            throw Error(`Expect: ${COLS} column(s), got ${vars.length}.`);

        result = {
            "username": vars[0],
            "start_time": new Date(Number(vars[1]) * 1000),
            "usage": Number(vars[3]),
            "total_usage": Number(vars[6]),
            "ip": vars[8],
            "balance": Number(vars[11])
        };

        if (!result.username ||
            isNaN(result.start_time.getTime()) ||
            isNaN(result.usage) ||
            isNaN(result.total_usage) ||
            !result.ip ||
            isNaN(result.balance))
            throw Error(`Failed to parse the status (${resp})`);

  profile:
    - login_usereg
    - url: http://usereg.tsinghua.edu.cn/user_info.php
      result: |
        let info = {};
        let tds = $('.maintd').map(function() { return $(this).text().trim(); });

        for (let i = 1; i < tds.length; i += 2)
            info[tds[i - 1]] = tds[i];

        let billing = info["用户组"];
        if (!billing)
            throw Error("Failed to get the billing group.");
        switch (billing) {
        case "在校生": billing = "student"; break;
        // TODO: Add case for teacher group.
        default:
            throw Error("unsupported");
        }

        result = {
            "name": info["姓名"],
            "billing": billing,
            "usage": parseFloat(info["使用流量(IPV4)"]),
            "balance": parseFloat(info["可用余额"])
        };

        if (Number.isNaN(result.usage) ||
            Number.isNaN(result.balance))
            throw Error(`Failed to parse the profile page.`);

    - url: http://usereg.tsinghua.edu.cn/modify_online_num.php
      result: |
        result = {
            "max_online_num": Number($("option[selected]").val())
        };

        if (isNaN(result.max_online_num))
            throw Error("Failed to get max_online_num.");

    - url: http://usereg.tsinghua.edu.cn/online_user_ipv4.php
      result: |
        result = $("tr ~ tr").map(function() {
            let row = $(this);
            let texts = row.children().map(function() { return $(this).text().trim(); });
            let COLS = 14;
            if (texts.length != COLS)
                throw Error(`Expect ${COLS} column(s), got ${texts.length}.`);

            let id = row.find("input").val();
            if (!id)
                throw Error("Failed to get session id.");

            let ip = texts[1];
            if (!ip)
                throw Error("Failed to get ip.");

            let start_time_str = texts[2].replace(" ", "T") + "+08:00";
            let start_time = new Date(start_time_str);
            if (isNaN(start_time.getTime()))
                throw Error(`Invalid start_time_str: ${start_time_str}.`);

            let usage_str = texts[3];
            if (!usage_str)
                throw Error(`usage_str is empty.`);
            let num = Number(usage_str.substr(0, usage_str.length - 1));
            let unit = usage_str[usage_str.length - 1].toUpperCase();

            let ratio = 1;
            switch (unit) {
              case 'B': ratio = 1;   break;
              case 'K': ratio = 1e3; break;  // TODO: Check the ratio.
              case 'M': ratio = 1e6; break;
              case 'G': ratio = 1e9; break;
            }
            let usage = Math.round(num * ratio);

            let mac = texts[7];
            if (!mac)
                mac = null;

            let device = texts[11];
            if (!device)
                device = null

            return {
                "id": id,
                "ip": ip,
                "start_time": start_time,
                "usage": usage,
                "mac": mac,
                "device": device
            };
        });

  logout_session:
    - login_usereg
    - method: POST
      url: http://usereg.tsinghua.edu.cn/online_user_ipv4.php
      params:
        action: drops
        user_ip: "{session_id},"
      result:
        ok: 下线请求已发送

  # history:
  #   - url: http://usereg.tsinghua.edu.cn/user_detail_list.php
  #     params:
  #       action: query
  #       start_time: 2013-02-01
  #       end_time: 2017-02-01
  #       offset: 65536

  logout:
    method: POST
    url: http://net.tsinghua.edu.cn/do_login.php
    params:
      action: logout
    result:
      ok: Logout is successful|You are not online

  customs:
    login_usereg:
      - method: POST
        url: http://usereg.tsinghua.edu.cn/do.php
        params:
          action: login
          user_login_name: "{username}"
          user_password: "{password.md5}"
        result:
          ok: ok
          unauthorized.username: 用户不存在
          unauthorized.password: 密码错误
