name: Tsinghua University

ssids:
  - Tsinghua
  - Tsinghua-5G

login:
  method: POST
  url: http://net.tsinghua.edu.cn/do_login.php
  params:
    action: login
    username: "{username}"
    password: "{MD5_HEX}{password.md5}"
    ac_id: "1"
  results:
    online: Login is successful|IP has been online, please logout
    unauthorized: E2531|E2553
    arrears: E2616|E3001|E3004

status:
  method: POST
  url: http://net.tsinghua.edu.cn/do_login.php
  params:
    action: check_online
  results:
    online: online
    offline: not_online

logout:
  method: POST
  url: http://net.tsinghua.edu.cn/do_login.php
  params:
    action: logout
  results:
    offline: Logout is successful|You are not online
